### ISSUE TITLE
[ENH] Add Unit type module

### ISSUE THREAD

**Issue by domthom21** [domthom21/eurocodedesign#10]
**Is your feature request related to a problem? Please describe.**
I would like to add python types for units with a new module eurocodedesign.units.

**Describe the solution you'd like**
I would like to add a unit module similar to astropy.units https://docs.astropy.org/en/stable/units/index.html
but with less overhead and less functionality add the start.
The units can than be used for function parametes and Co.

`from eurocodesign.units import (mm, newton)

l: mm = 50
`
Conversion between units will be added later, like mm_2 to cm_2, pascal to N/mm² and so on.

**Describe alternatives you've considered**
1. We could import astropy.units and create wrappers for our units, but this would add a dependancy and isn't a lightweight solution.
2. Sympy and scipy or pint are other untyped python librarys with unit functionality, however there performance is slow because of their dynamic type checks.

**Additional context**
Proposed units, further suggestions are welcomed:
* newton
* mm
* mm_2
* mm_3
* mm_4
* celsius
* megapascal

Maybe we should add another module eurodesign.types for partial safety factor type, eta, and other?

**Comment by nc-hsu** [comment]
Consider also MPa or megapascal. it would be used quite frequently I think

**Comment by domthom21** [comment]
Pull request merged, for further steps see #37
