### ISSUE TITLE
[ENH] Add HD and HL steel profiles to profile database

### ISSUE THREAD

**Issue by nc-hsu** [domthom21/eurocodedesign#86]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for the wide and extra wide column  HD and HL profiles described in DIN EN 10365 (2017). These profiles are often required in the design of larger buildings and it would be useful to include them in the profile database 

**Describe the solution you'd like**
Add the HD and HL profiles to the section database as has been done for HEA, HEB profiles, etc.

**Comment by domthom21** [comment]
see #87
